name: ReportSystem
main: com.example.reportsystem.platform.bukkit.BukkitBootstrap
version: 3.0.0
api-version: 1.20
author: you
commands:
  report:
    description: Submit a report
    usage: /report <type> <category> [...]
  reports:
    description: Staff report management
    usage: /reports
  reporthistory:
    description: View closed reports
    usage: /reporthistory
