# === ReportSystem – Default Configuration ===

# ------------------------------------------------------------------------------------
# CORE
# ------------------------------------------------------------------------------------
allow-self-report: true                  # Allow players to report themselves?
stack-window-seconds: 600                # Seconds to merge ("stack") identical reports (same target/type/category)
export-html-chatlog: true                # If true, chat logs export to HTML (used when web viewer is enabled)
html-export-dir: "html-logs"             # Folder under the plugin data directory for HTML exports
reports-per-page: 10

# Permissions
staff-permission: "reportsystem.reports"          # Staff can use /reports, bypass cooldown, view protected web pages, etc.
notify-permission: "reportsystem.notify"          # Staff who should receive ingame notifications about new reports
force-claim-permission: "reportsystem.forceclaim" # Staff who may override someone else’s claim
admin-permission: "reportsystem.admin"            # Admin-only: /reports reload, /reports logoutall, force-claim override fallback

# ------------------------------------------------------------------------------------
# REPORT COOLDOWN
# ------------------------------------------------------------------------------------
# Players must wait this long between /report commands.
# Users with staff-permission bypass this cooldown.
report-cooldown-seconds: 60

# ------------------------------------------------------------------------------------
# INLINE PREVIEW (safe inline chat previews)
# ------------------------------------------------------------------------------------
preview-lines: 10
preview-line-max-chars: 200

# ------------------------------------------------------------------------------------
# PUBLIC URLS FOR LINKS SHOWN IN CHAT
# ------------------------------------------------------------------------------------
# Leave blank by default (no private domain committed). If you have a public domain later,
# set EITHER public-base-url OR http-server.external-base-url (prefer public-base-url).
public-base-url: ""                      # e.g. "https://reports.example.com"

http-server:
  enabled: false                         # Built-in tiny web server to serve html-logs/
  external-base-url: ""                  # e.g. "https://reports.example.com" (used for links when public-base-url is blank)
  bind: "0.0.0.0"                        # Listen address
  port: 8085
  base-path: "/"                         # Mount path (keep "/" unless you know you need a subpath)

# ------------------------------------------------------------------------------------
# LIGHTWEIGHT WEB AUTH FOR HTTP SERVER
# ------------------------------------------------------------------------------------
auth:
  enabled: false
  cookie-name: "rsid"
  session-ttl-minutes: 1440              # Sliding session TTL (minutes)
  code-ttl-seconds: 120                  # One-time code lifetime (seconds) for /reports auth
  code-length: 6
  secret: "change-me"                    # Change in production; used for signing session ids
  open-paths:                            # Paths accessible without auth (when auth is enabled)
    - "/login"
    - "/favicon.ico"
  require-permission: true               # Require staff-permission to run /reports auth and receive a code

# ------------------------------------------------------------------------------------
# DISCORD WEBHOOK (optional)
# ------------------------------------------------------------------------------------
discord:
  enabled: false
  webhook-url: ""
  username: "ReportSystem"
  avatar-url: ""
  timeout-ms: 4000

# ------------------------------------------------------------------------------------
# MULTI-FACTOR PRIORITY SCORING
# ------------------------------------------------------------------------------------
# Effective Score = Sum( weight_i * factor_i ), for enabled factors only.
priority:
  enabled: true

  # Enable/Disable individual factors
  use-count: true
  use-recency: true
  use-severity: true
  use-evidence: true
  use-unassigned: true
  use-aging: true
  use-sla-breach: true

  # Weights (importance)
  w-count: 2.0
  w-recency: 2.0
  w-severity: 3.0
  w-evidence: 1.0
  w-unassigned: 0.5
  w-aging: 1.0
  w-sla-breach: 4.0

  # Shaping
  tau-ms: 900000           # 15 minutes exponential time constant for recency decay

  # Severity map "<typeId>/<categoryId>": weight
  severity-by-key:
    "player/cheat": 3.0
    "server/crash": 2.5
    "player/chat": 1.0
    "player/ad": 1.5

  # SLA targets (minutes)
  sla-minutes:
    "player/cheat": 5
    "server/crash": 2
    "player/chat": 15

# ------------------------------------------------------------------------------------
# MESSAGES / LOCALIZATION
# ------------------------------------------------------------------------------------
messages:
  prefix: "<gray>[<blue>Reports</blue>]</gray> "
  no-permission: "<red>You don't have permission.</red>"

  # /report UX
  usage-report: "Usage: /report <type> <category> [<target>] <reason...>"
  invalid-type: "Unknown type or category: %type%/%cat%"
  self-report-denied: "You cannot report yourself."
  report-stacked: "Report stacked into #%id% (now x%count%)"
  report-filed: "Report filed! (ID #%id%)"
  report-cooldown: "<red>You must wait %seconds% seconds before filing another report.</red>"

  # Common
  not-found: "No such report: #%id%"
  closed: "Closed report #%id%"
  assigned: "Assigned report #%id% to %assignee%"
  unassigned: "Unassigned report #%id%"
  already-unassigned: "Report #%id% is not assigned."
  search-empty: "No matching reports."
  search-header: "Search: %query% (%scope%)"
  page-empty: "No open reports."
  page-header: "Reports Page %page%/%pages%"
  page-header-filtered: "Reports (%type%/%cat%) Page %page%/%pages%"
  reloaded: "ReportSystem reloaded."
  chatlog-none: "No chat messages were captured for this report."

  # Report history (closed)
  history-page-empty: "No closed reports."
  history-page-header: "Closed Reports Page %page%/%pages%"
  already-open: "Report #%id% is already open."
  reopened: "Reopened report #%id%"
  tip-reopen: "Reopen this report"

  # Buttons / tooltips (used everywhere)
  label-expand: "^"                       # unified EXPAND label (used in lists, search, notifications)
  tip-expand: "Click to expand"
  tip-open-browser: "Open in browser"
  tip-open-login: "Open login page"
  auth-no-base-url: "<red>No public URL configured. Set public-base-url or http-server.external-base-url.</red>"
  tip-prev: "Previous page"
  tip-next: "Next page"
  tip-reload: "Reload reports"
  tip-close: "Close this report"
  tip-chat: "View chat logs"
  tip-jump-server: "Connect to this server"
  tip-assign-me: "Assign to me"
  tip-unassign: "Unassign"
  tip-force-claim: "Force-claim"

  # Hover tooltips for list line segments
  tip-target: "Target: %name%"
  tip-assigned: "Assigned: %name%"
  tip-server: "Server: %name%"

  # Expanded view
  expanded-header: "Report #%id% (%type% / %category%)"
  expanded-server-line: "<gray>Server:</gray> <white>%server%</white>"
  expanded-lines:
    - "<gray>Reported:</gray> <white>%target%</white> <gray>by</gray> <white>%player%</white>"
    - "<gray>When:</gray> <white>%timestamp%</white>"
    - "<gray>Count:</gray> <white>%count%</white>"
    - "<gray>Reason(s):</gray> <white>%reasons%</white>"
    - "<gray>Status:</gray> <white>%status%</white>"
    - "<gray>Assignee:</gray> <white>%assignee%</white>"

  # Chat log viewer (web and inline)
  open-chatlog-label: "Open chat log"
  auth-code-ttl-s: "120"
  jump-command-template: "/server %server%"

# ------------------------------------------------------------------------------------
# DYNAMIC REPORT TYPES
# ------------------------------------------------------------------------------------
# You can add/remove categories freely; type/category ids are what you use on /report.
report-types:
  player:
    display: "Player"
    categories:
      chat: "Chat"
      cheat: "Cheating"
      ad: "Advertising"
      grief: "Griefing"
  server:
    display: "Server"
    categories:
      crash: "Crash"
      lag: "Lag"
      dupe: "Duplication Bug"

# ------------------------------------------------------------------------------------
# STACK BADGE THRESHOLDS & COLORS (ui only)
# ------------------------------------------------------------------------------------
stack-thresholds:
  yellow: 3
  gold: 5
  red: 10
  dark-red: 15

stack-colors:
  yellow: "<yellow>"
  gold: "<gold>"
  red: "<red>"
  dark-red: "<dark_red>"
