# ReportSystem v2.1 config

allow-self-report: false
stack-window-seconds: 600
export-html-chatlog: true
html-export-dir: "html-logs"

reports-per-page: 10
staff-permission: "reportsystem.reports"
notify-permission: "reportsystem.notify"

# Inline chat preview safety (used when export-html-chatlog=false)
preview-lines: 10
preview-line-max-chars: 200

# If set, http(s) links are used for exported logs
public-base-url: ""

# Priority sorting of open reports
priority-sorting: true
tie-breaker: "newest"     # or "oldest"

# Stack count thresholds -> badge color
stack-thresholds:
  yellow: 3
  gold: 5
  red: 10
  dark-red: 15

# Colors used for (xN) badge; can be any MiniMessage color tag
stack-colors:
  yellow: "<yellow>"
  gold: "<gold>"
  red: "<red>"
  dark-red: "<dark_red>"

# Optional embedded HTTP server to serve html-logs (clickable links without a domain)
http-server:
  enabled: false
  external-base-url: "http://YOUR_PROXY_IP:8085"
  bind: "0.0.0.0"
  port: 8085
  base-path: "/"

discord:
  enabled: false
  webhook-url: "https://discord.com/api/webhooks/put-yours-here"
  username: "ReportSystem"
  avatar-url: ""
  timeout-ms: 4000

messages:
  prefix: "<gray>[<aqua>ReportSystem</aqua>]</gray> "

  no-permission: "<red>You don't have permission.</red>"
  usage-report: "<yellow>Usage:</yellow> /report <type> <category> <target|reason...> <reason...>"
  invalid-type: "<red>Unknown report type:</red> <white>%type%</white>"
  invalid-category: "<red>Unknown category:</red> <white>%category%</white>"
  self-report-denied: "<red>You cannot report yourself.</red>"
  player-not-found: "<red>Player not found:</red> <white>%target%</white>"

  report-filed: "<green>Report filed!</green> <gray>(ID:</gray> <white>#%id%</white><gray>)</gray>"
  report-stacked: "<green>Report stacked</green> into <white>#%id%</white> <gray>(now x%count%)</gray>"
  open-count: "<gray>Open reports:</gray> <white>%count%</white>"
  page-header: "<gray>Reports Page</gray> <white>%page%</white><gray>/<white>%pages%</white></gray>"
  page-empty: "<yellow>No open reports.</yellow>"
  expanded-header: "<aqua>Report #%id%</aqua> <gray>(%type% / %category%)</gray>"
  expanded-lines:
    - "<gray>Reported:</gray> <white>%target%</white> <gray>by</gray> <white>%player%</white>"
    - "<gray>When:</gray> <white>%timestamp%</white>"
    - "<gray>Count:</gray> <white>%count%</white>"
    - "<gray>Reason(s):</gray> <white>%reasons%</white>"
    - "<gray>Status:</gray> <white>%status%</white>"
    - "<gray>Assignee:</gray> <white>%assignee%</white>"
  expanded-actions: "<gray>[</gray><green><click:run_command:'/reports close %id%'>Close</click></green><gray>] [</gray><aqua><click:run_command:'/reports chat %id%'>Chat Logs</click></aqua><gray>]</gray>"
  closed: "<green>Closed report #</green><white>%id%</white><gray>.</gray>"
  not-found: "<red>No such report:</red> <white>#%id%</white>"
  chatlog-none: "<yellow>No chat messages were captured for this report.</yellow>"
  chatlog-open-url: "<gray>Open chat log:</gray> <click:open_url:'%url%'><underlined><aqua>%url%</aqua></underlined></click>"
  reloaded: "<green>ReportSystem reloaded.</green>"

  # History (closed)
  history-page-header: "<gray>Closed Reports Page</gray> <white>%page%</white><gray>/<white>%pages%</white></gray>"
  history-page-empty: "<yellow>No closed reports.</yellow>"
  reopened: "<green>Reopened report #</green><white>%id%</white><gray>.</gray>"
  already-open: "<yellow>Report #</yellow><white>%id%</white><yellow> is already open.</yellow>"
  history-expanded-actions: "<gray>[</gray><green><click:run_command:'/reporthistory reopen %id%'>Reopen</click></green><gray>]</gray>"

  # Assign / Search
  assigned: "<green>Assigned report #</green><white>%id%</white><green> to </green><white>%assignee%</white><gray>.</gray>"
  unassigned: "<green>Unassigned report #</green><white>%id%</white><gray>.</gray>"
  already-unassigned: "Report #%id% is not assigned."
  search-header: "<gray>Search:</gray> <white>%query%</white> <gray>(%scope%)</gray>"
  search-empty: "<yellow>No matching reports.</yellow>"

  # Tooltips (hover text) for buttons
  tip-expand: "Click to expand"
  tip-prev: "Previous page"
  tip-next: "Next page"
  tip-assign-self: "Assign to yourself"
  tip-unassign: "Remove assignee"
  tip-open-browser: "Open in browser"
  tip-copy-path: "Copy local path"

# Dynamic report types and categories
report-types:
  player:
    display: "Player"
    categories:
      chat: "Chat Report"
      cheating: "Cheating Report"
  bug:
    display: "Bug"
    categories:
      network: "Network Bug"
      server: "Server Bug"
